### ISSUE TITLE
🐞 Bug - Empty user and password for SMTP

### ISSUE THREAD

**Issue by B-Prod** [SocialGouv/domifa#3579]
### 🖥️ Site(s) concerné(s)

- [ ] DomiFa - côté structures
- [ ] Mon DomiFa - portail domiciliés
- [ ] Admin DomiFa
- [ ] Metabase

### 🚫 Description du problème

When defining the SMTP credentials, we need to specify an empty user and password.

This leads to the following error, as the related variables `DOMIFA_MAIL_SMTP_MAILTRAP_USER` and `DOMIFA_MAIL_SMTP_MAILTRAP_PASSWORD` are set as required and does not allow empty strings:

```shell
[configParser] missing required env value "DOMIFA_MAIL_SMTP_MAILTRAP_USER"
```

However in local, we would like to use mailhog with the following settings:
```yaml
      DOMIFA_MAIL_SMTP_MAILTRAP_HOST: mailhog
      DOMIFA_MAIL_SMTP_MAILTRAP_PORT: 1025
      DOMIFA_MAIL_SMTP_MAILTRAP_USER: ''
      DOMIFA_MAIL_SMTP_MAILTRAP_PASSWORD: ''
```

Moreover, the variable `DOMIFA_TIPIMAIL_FROM_EMAIL` is required, even if the chosen email provider is MAILTRAP.

### 🔮 Comportement attendu

Make the `DOMIFA_TIPIMAIL_FROM_EMAIL` environment variable required only if the mail provider is TIPIMAIL.

Allow empty string for user and password in mail configuration.
