### ISSUE TITLE
🐞 Bug - services not starting locally

### ISSUE THREAD

**Issue by B-Prod** [SocialGouv/domifa#3585]
### 🖥️ Site(s) concerné(s)

- [X] DomiFa - côté structures
- [X] Mon DomiFa - portail domiciliés
- [X] Admin DomiFa
- [ ] Metabase

### 🚫 Description du problème

The 3 following services do not build:
- portail-admins
- portail-usagers
- frontend

To reproduce the issue on the `frontend` application, we just create a very simple `docker-compose.yml` file based on the provided file `docker-compose.local.yml`, with the following contents:

```yaml
services:
   frontend:
     container_name: domifa-frontend
     hostname: domifa-frontend
     build:
       context: _scripts/dev
       dockerfile: local-node.dockerfile
     command: tail -f /dev/null
     working_dir: /app/packages/frontend
     volumes:
       - ./:/app:delegated
     ports:
       - 4200:4200
     env_file:
       - ./.env
     environment:
       TZ: Europe/Paris
```

Then we start the service:

```shell
docker compose -f docker-compose.yml up -d
docker exec -it domifa-frontend bash
yarn install
yarn start
```

The `yarn start` command throws the following error:

```shell
  ➜  Network: http://172.18.0.7:4200/
node:events:495
      throw er; // Unhandled 'error' event
      ^
Error: spawn xdg-open ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:290:12)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [ 'http://localhost:4200/' ]
}
Node.js v18.20.0
```

### 🔮 Comportement attendu

The `yarn start` command should run without errors, allowing to access the application through the expected URL.
